if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    include(MEMVIZClangFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    include(MEMVIZMSVCFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    message(WARNING "Using gcc. This project targets clang.")
    include(MEMVIZClangFlags)
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()
